In [2]:
import torch

In [3]:
randint = torch.randint(-100, 100, (6,))

print(randint)

tensor([ 46, -22, -65,  -6,  82,  40])


In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])